[package]
name = "streamcatcher"
version = "0.1.0"
license = "MIT"
homepage = "https://github.com/FelixMcFelix/streamcatcher"
repository = "https://github.com/FelixMcFelix/streamcatcher.git"
authors = ["Kyle Simpson <kyleandrew.simpson@gmail.com>"]
keywords = []
categories = []
description = ""
readme = "README.md"
documentation = "https://docs.rs/streamcatcher"
edition = "2018"

[features]
default = []
async = ["futures"]
tokio-compat = ["async", "tokio"]

[dependencies]
parking_lot = "0.11"

[dependencies.futures]
optional = true
version = "0.3"

[dependencies.tokio]
optional = true
version = "0.2"