name: Build and Test (Stable)

on:
  push:
    branches: [ stable, breaking ]
  pull_request:
    branches: [ stable, breaking ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
