name: Safety

on:
  push:
    branches: [ stable, breaking ]
  pull_request:
    branches: [ stable, breaking ]

env:
  CARGO_TERM_COLOR: always

jobs:
  loom_safety:
    name: "Loom Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Run safety tests
      run: RUSTFLAGS="--cfg loom --cfg loom_nightly" cargo +nightly test --verbose --all-features safety
